<?php include_once("fancylinks.php"); ?>

            <?php TwoLinks ("sites/books","e-Books","(nw)"); ?>
            <?php TwoLinks ("sites/drss","DRSS","(nw)"); ?>
            <?php TwoLinks ("sites/bernd2009/public_html","Bernd-2009","(nw)"); ?>
            <?php TwoLinks ("temple/","template testing","(nw)"); ?>
            <?php TwoLinks ("sites/bernd2009/public_html/test/","satview download","(nw)"); ?>
		            <?php TwoLinks ("sites/toystore/catalog","toystore","(nw)"); ?>
		            <?php TwoLinks ("sites/toystore/catalog/admin/","toystore admin","(nw)"); ?>
      <?php TwoLinks("pictures/pics/","pictures","(nw)"); ?>
      <?php TwoLinks("papers/online-marketing/","marketing papers","(nw)"); ?>
      <?php TwoLinks("downloadable/","downloadable files","(nw)"); ?>
      <?php TwoLinks("sites/books/cmake/cmake.html","Cmake reference","(nw)"); ?>
      <?php TwoLinks("sites/books/git_manual/user-manual.html","Git reference","(nw)"); ?>
      <?php TwoLinks("sites/books/php_manual/index.html","PHP reference","(nw)"); ?>
      <a href="phpMyAdmin3/index.php" > MySql-Admin </a>
