<?php include_once("fancylinks.php"); ?>
<ul class="nodots">
<li>
<?php TwoLinks ("https://www.sixxs.net/",
                "SixXs.net","(nw)"); ?>
                </li>
<li>
<?php TwoLinks ("http://berndhs.wordpress.com",
                "Bernd's Blog at Wordpress",
                "(nw)"); ?>
</li>
<li>
<?php TwoLinks ("http://www.ripe.net/ipv6-address-types",
                "IPv6 address types on RIPE","(nw)"); ?>
                </li>
<li>
<?php TwoLinks ("http://bernd-stramm.com/andmore/reportstats.php?quiet",
               "Short Counter Report");?>
</li>
<li>
<?php TwoLinks ("http://berndhs.users.sourceforge.net",
                "BerndHS at Sourceforge.net"); ?>
</li>
<li>
<a href="http://www.brocku.ca/library/" > Brock Library </a><br>
<li>			<?php TwoLinks("http://www.stramm.ca/newstore/","New Store Top","(nw)"); ?>
			
</li>
<li>			<?php TwoLinks("http://www.stramm.ca/newstore/catalog","New Store Client","(nw)"); ?>
			
</li>
<li>			<?php TwoLinks("http://www.stramm.ca/newstore/catalog/admin","New Store Admin","(nw)"); ?>
			
</li>
<li><?php TwoLinks("http://mini-web.sourceforge.net/","Miniweb on Sourceforge","nw"); ?>

</li>
<li><?php TwoLinks("http://drss.sourceforge.net/","DRSS on Sourceforge","nw"); ?>

</li>
<li><?php TwoLinks("http://egalite.sourceforge.net/","Egalite on Sourceforge","nw"); ?>
</li>
<li><?php TwoLinks("http://notably.sourceforge.net/","Notably on Sourceforge","nw"); ?>
</li>
<li><?php TwoLinks("http://www.sourceforge.net/projects/egalite","Égalité! on Sourceforge","nw"); ?>
</li>
<li><?php TwoLinks ("http://chronicon.sourceforge.net","Chronicon on SF","nw");?>
</li>
<li><a href="http://www.bernd-stramm.com/" > Bernd-Stramm.com </a><br>
</li>
<li><a href="http://freibier.bravehost.com" > Bernd-Bravenet </a><br>
</li>
<li><a href="http://cell.raw.net" > Cell </a><br>
</li>
<li><a href="http://miniscsim.sourceforge.net" > MiniscSim </a><br>
</li>
<li><a href="http://www.germanshepherddog.ca/marco" > Dog </a><br>
</li>
<li><a href="http://www.daytonselfstorage.com/admin" > Dayton Admin </a><br>
</li>
<li><a href="http://www.reflective-computing.com/">Reflective</a><br>
</li>
</ul>
